/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package de.karfau.parallelpaint.model.vo
{
	import de.karfau.parallelpaint.core.IComparable;
	import de.karfau.parallelpaint.core.elements.IClonable;
	
	import mx.collections.ArrayCollection;
	
	[Bindable]
	[RemoteClass(alias="model.Drawing")]
	/**
	 * This is the ValueObject for communication with BE.
	 */
	public class Drawing extends AbstractValueObject implements ValueObject
	{
		
		public var author:String;
		public var elements:ArrayCollection = new ArrayCollection();
		
		public var versionOf:Number;
		public var versionTag:String;
		
		public function toString ():String {
			return "Drawing{# " + id + ", with " + (elements ? elements.length : 0) + " elements}";
		}
		
		public function idString ():String {
			return "ppd_" + id;
		}
	
	}
}