/**
 * Generated by Gas3 v2.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package de.karfau.parallelpaint.model.vo
{
	import de.karfau.parallelpaint.core.elements.IElement;

	import flash.utils.getQualifiedClassName;

	[Bindable]
	[RemoteClass(alias="model.Element")]
	/**
	 * This is the ValueObject for communication with BE.
	 */
	public class ElementVO extends AbstractValueObject implements ValueObject
	{
		public var drawingId:Number = -1;

		public var type:String;

		public var elemOrder:uint;
		public var elemVersion:Number;

		[ArrayElementType("Number")]
		public var coords:Array = [];

		public var styleXML:String;

		//public var group:String;

		public function ElementVO (drawingId:Number=0) {
			this.drawingId = drawingId;
			super();
		}

	}
}